M48
; DRILL file {KiCad 8.0.5} date 2024-09-26T09:53:26+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-26T09:53:26+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.200
%
G90
G05
T1
X74.325Y-149.098
X92.71Y-130.713
X92.71Y-167.483
X111.095Y-149.098
M30
