M48
; DRILL file {KiCad 8.0.5} date 2024-09-26T10:19:18+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-26T10:19:18+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.000
%
G90
G05
T1
X98.0Y-77.4
X98.0Y-100.4
X156.0Y-77.4
X156.0Y-100.4
M30
